### PR TITLE
fixed  `ElementOverlayBox` text rotation

### LINKED ISSUE #85: When using `pcbRotation` the pads rotate in the opposite direction.
repro update pcb-viewer in snippet and try to use `pcbRotations`
Image

```
export default () => {
  return (
    <board height="43.18mm" width="18.54mm">
      <chip
        manufacturerPartNumber="ATmega328P"
        name="U1"
        schX={0}
        schY={8}
        pcbX={0}
        pcbY={-8}
        footprint="qfp32"
        pcbRotation={45}
      />
    </board>
  )
}
```
original issue was closed:
https://github.com/tscircuit/footprinter/issues/93

### PR DESCRIPTION
**Pull request by Abse2001**
/closes #85

https://github.com/user-attachments/assets/733877f4-9f96-4f64-91d9-859d80e544c5

### CODE REVIEW

**Review by ShiboSoftwareDev — APPROVED** [review]
looks good to me

**Review by seveibar — APPROVED** [review]
/tip $20

**Comment by seveibar** [comment]
I'm not sure i can tip on non-bountied issues tho- lmk if it doesn't work!

**Comment by zcesur** [comment]
Zaf from Algora here. The problem was Github's different treatment of review vs issue comments. We extended our bot to also listen to review comments, so this should work going forward. Cheers!

**Pull request merged**
