### PR TITLE
feat: add the buldge in the trace

### PR DESCRIPTION
**Pull request by imrishabh18**
Closes - #36 

Screenshot 2024-08-17 at 1 00 13 AM

### CODE REVIEW

**Review by seveibar — CHANGES_REQUESTED** [review]
At each offset, the width should be equal to the defined offset width. Right now you're making the point between offsets wider.

Also there should be no curves

**Comment by imrishabh18** [comment]
But the offset as well as the point between the offsets should be of the same width right? Just that the transition is what I need to take care between the routes width


Screenshot 2024-08-17 at 7 16 44 PM

**Comment by imrishabh18** [comment]
@seveibar Is this how the convergence at the start and end should look like?

Screenshot 2024-08-17 at 11 18 37 PM

**Comment by seveibar** [comment]
No, i can try to give you an equation shortly, but it should always linearly interpolate, there isnt any special behavior as you get close to a corner

**Comment by seveibar** [comment]
image


@imrishabh18 here's a method you can use:

```ts
interface Point {
  x: number;
  y: number;
  width?: number;
}

function getExpandedStroke(
  strokeInput: (Point | [number, number] | number[])[],
  defaultWidth: number
): Point[] {
  if (strokeInput.length < 2) {
    throw new Error("Stroke must have at least two points");
  }
  
  const stroke: Point[] = strokeInput.map(point => {
    if (Array.isArray(point)) {
      return { x: point[0], y: point[1] };
    }
    return point as Point;
  });

  const leftSide: Point[] = [];
  const rightSide: Point[] = [];

  function getNormal(p1: Point, p2: Point): Point {
    const dx = p2.x - p1.x;
    const dy = p2.y - p1.y;
    const length = Math.sqrt(dx * dx + dy * dy);
    return { x: -dy / length, y: dx / length };
  }

  function addPoint(point: Point, normal: Point, factor: number, width: number) {
    const halfWidth = width / 2;
    const newPoint = {
      x: point.x + normal.x * halfWidth * factor,
      y: point.y + normal.y * halfWidth * factor,
    };
    if (factor > 0) {
      leftSide.push(newPoint);
    } else {
      rightSide.unshift(newPoint);
    }
  }

  // Handle the first point
  const firstNormal = getNormal(stroke[0]!, stroke[1]!);
  const firstWidth = stroke[0]!.width ?? defaultWidth;
  addPoint(stroke[0]!, firstNormal, 1, firstWidth);
  addPoint(stroke[0]!, firstNormal, -1, firstWidth);

  // Handle middle points
  for (let i = 1; i < stroke.length - 1; i++) {
    const prev = stroke[i - 1]!;
    const current = stroke[i]!;
    const next = stroke[i + 1]!;

    const normalPrev = getNormal(prev, current);
    const normalNext = getNormal(current, next);

    // Calculate miter line
    const miterX = normalPrev.x + normalNext.x;
    const miterY = normalPrev.y + normalNext.y;
    const miterLength = Math.sqrt(miterX * miterX + miterY * miterY);

    const currentWidth = current.width ?? defaultWidth;

    // Check if miter is too long (sharp corner)
    const miterLimit = 2; // Adjust this value to control when to bevel
    if (miterLength / 2 > miterLimit * (currentWidth / 2)) {
      // Use bevel join
      addPoint(current, normalPrev, 1, currentWidth);
      addPoint(current, normalNext, 1, currentWidth);
      addPoint(current, normalPrev, -1, currentWidth);
      addPoint(current, normalNext, -1, currentWidth);
    } else {
      // Use miter join
      const scale = 1 / miterLength;
      addPoint(current, { x: miterX * scale, y: miterY * scale }, 1, currentWidth);
      addPoint(current, { x: miterX * scale, y: miterY * scale }, -1, currentWidth);
    }
  }

  // Handle the last point
  const lastNormal = getNormal(
    stroke[stroke.length - 2]!,
    stroke[stroke.length - 1]!
  );
  const lastWidth = stroke[stroke.length - 1]!.width ?? defaultWidth;
  addPoint(stroke[stroke.length - 1]!, lastNormal, 1, lastWidth);
  addPoint(stroke[stroke.length - 1]!, lastNormal, -1, lastWidth);

  // Combine left and right sides to form a closed polygon
  return [...leftSide, ...rightSide];
}
```


Here's the conversation I used to generate it (make sure to scroll down to the bottom-most artifact) https://claude.ai/share/f448873d-bac2-4734-a878-c12a5afa0b2c

**Comment by seveibar** [comment]
@imrishabh18 if you want to play with the algo online i uploaded it to repl.it https://replit.com/join/hartauagda-seveibar

**Comment by seveibar** [comment]
@imrishabh18 we might label this stroke behavior as `pcb_trace.route_thickness_mode: "interpolate"`, because it's actually not super common (although IMO it's the best one) a lot of programs will use an alternate method that's easier to compute collisions for which we might call `route_thickness_mode: "rounded_segments"` (shown below)

image

**Comment by imrishabh18** [comment]
@seveibar Take a look now. Will the offset circle width will also be this big, or it can be just a point?

Screenshot 2024-08-18 at 5 31 58 PM

**Comment by seveibar** [comment]
This can be future work but trace hints should show the width as a second circle on the offset point, then the polygon trace thats drawn in transparent red here should be fully red and should be drawn in the render function for a trace

I will create a wireframe showing what that looks like so we can just take this as incremental progress for now


A fill was added to the circles recently that i think is a bit confusing. We'll have to play with it (maybe in a future PR) but i think using an invert filter on the stroke (similar to dimension lines from the "d" key press where the color auto-inverts thanks to css) would be a better option than a fill

**Comment by seveibar** [comment]
Ok i was going to accept but i think its a slight regression unless we move this code to a trace render rather than a trace hint render. Will probably into this

**Comment by seveibar** [comment]
Ok following up with more information.

* The tracehint should NOT draw the trace- the trace should draw the trace
* The tracehint should show the width that the trace will get at each offset and the user should be able to "click and drag" to make the trace thicker in the pcb viewer
* The tracehint should have mixed-blend-mode: difference, same as the dimension overlay as shown in the code screenshot below
* There should be two circles on a trace hint _when the trace_width is defined_. One circle corresponds to the trace_width at that offset. If the trace_width isn't defined- the user hasn't specified their desired width at that point
* This is not needed for the initial PR, but there should be a square that the user can click and drag to adjust the trace_width, when they click and drag the square, it emits an "EditEvent"

image


image


we're getting closer- I didn't have a design totally in mind when we started so I can do a bit better next time, the only thing I knew is that we wanted to support interpolated traces, but I didn't realize we were editing the trace hint this time because of the same color etc.

**Comment by imrishabh18** [comment]
@seveibar Can we close this PR labelled as progress? Take a look at this https://pcb-viewer-9lyo8cwia-tscircuit.vercel.app/?path=/story/tracehint--trace-hint-example or let me know if something else also needs to be added. I will add and then we can merge this

**Review by seveibar — COMMENTED** [review]
ok let's merge as an incremental step https://github.com/tscircuit/pcb-viewer/issues/38

**Pull request merged**
