### PR TITLE
feat: add trace width

### PR DESCRIPTION
**Pull request by imrishabh18**
Closes - https://github.com/tscircuit/tscircuit/issues/264

The `width` is changeable

Screenshot 2024-08-13 at 1 51 41 AM

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
this isn't quite right, i would merge this as "progress" but generally speaking we should only apply the trace width for the hint, then fall back to the previous "default" trace width.

For most designs with a thick trace, you won't be able to have a constant trace width, in fact each "offset" inside of a tracehint should be able to have a width specified. This way you can work the trace through tight areas

image

**Comment by imrishabh18** [comment]
@seveibar I didn't get what you mean't by your comment. I was having the basic idea that if `traceWidth` is passed as a prop to `<tracehint />` then you use that width. Do you mean that the tracehint which the user edit's like in this video that needs to be changed?

https://github.com/user-attachments/assets/ba9f0596-1544-4b17-8a9b-71702b3858c0

**Comment by seveibar** [comment]
@imrishabh18 each point on the route can has it's own trace width, then the line will shrink or grow to fit the traceWidth at each point along the route.

image

image

**Comment by imrishabh18** [comment]
I see, so for soup to look like that the `traceWidth` prop value should be passed inside the offsets right? Like this for that traceHint to be of that size?

Screenshot 2024-08-14 at 12 57 27 AM

**Comment by seveibar** [comment]
@imrishabh18 yep both are acceptable syntaxes that do slightly different things

**Comment by imrishabh18** [comment]
@seveibar This is how the trace_widths can be modified according to the route.

Screenshot 2024-08-16 at 2 14 28 AM

**Comment by seveibar** [comment]
@imrishabh18 looks a bit strange, will pull and take a look

**Review by seveibar — APPROVED** [review]
Actually i just dodnt understand your approach, this is quite clever, nice job!!!!

**Comment by seveibar** [comment]
For the example i might choose a more dramatic trace width difference, eg 20, 1

**Comment by imrishabh18** [comment]
This is how it looks for the dramatic 20 width 🤔. Now I get what you mean't by that buldge

Screenshot 2024-08-16 at 2 20 26 AM

**Comment by imrishabh18** [comment]
This will need more work, and could be complex for making that buldge. Will merge this as a decent progress and then can work more upon it

**Pull request merged**
