### PR TITLE
feat: Render inside Trace

### PR DESCRIPTION
**Pull request by imrishabh18**
Closes - #41 

Have added this extra trace point to show the polygon.

https://github.com/user-attachments/assets/284fc1cc-f023-4287-8189-bfd5e32b8fb7

### CODE REVIEW

**Comment by imrishabh18** [comment]
@seveibar This is a bit complex, so I am making draft PR's. 

Question:
- The circle will be added in the middle of the routes like this, inside `pcb_trace` for the interpolated case only?
Screenshot 2024-08-28 at 12 29 48 AM

**Review by seveibar — APPROVED** [review]
looks pretty good to me! glad you also implemented the constant thickness!

**Comment by seveibar** [comment]
@imrishabh18 why is it so spikey, can pull the code and take a look but it does seem something is a bit off, like there's a bunch of rects inside the trace

**Comment by imrishabh18** [comment]
Let me take a look again, it's because of the shape used to fill the polygon is `square`. I will try other shapes as well and check

**Comment by imrishabh18** [comment]
@seveibar I think this is the correct approach of drawing it in the canvas and this looks good!

https://github.com/user-attachments/assets/91747e7d-d038-4570-bb22-6922f1ad0703

**Comment by seveibar** [comment]
That looks great!!!!

**Pull request merged**
